# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""
This script applies a temperature overlap model to L1 data for monitoring changes in the overlap function generated by the rest of the code.
It generates plots to visualize the overlap functions and their relative differences.
It also applies the overlap correction to the L1 data and generates plots for the corrected data for a quick model validation.

This code is designed to be run as a standalone script and run on a monthly basis to monitor changes in the overlap function.

Code inspired from Melania but refactored and simplified
   
@author Eric Sauvageat, 2025

"""
import glob
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib as mpl
import matplotlib.pyplot as plt

# Constants
MAX_RANGE = 800 # Maximum range for plotting the overlap function (in meters)
T=25 # Ref temperature in Celsius for the overlap function calculation (only relevant for comparison of monthly temperature models)

# Set matplotlib parameters for better visualization
params = {'legend.fontsize': 8,
    'axes.titlepad':10,
    'figure.figsize': (15, 5),
    'axes.labelsize': 10,
    'axes.titlesize':10,
    'axes.linewidth':2,
    'xtick.labelsize':10,
    'ytick.labelsize':10,
    'ytick.major.size': 5,
    'xtick.major.size': 5,
    'xtick.minor.size': 3
    }
plt.rcParams.update(params)

def compare_overlap_functions(location, inst_id, path_temp_model1, path_temp_model2, outfolder):
    '''
    Compare two overlap models for a given location and instrument ID. This is used to monitor changes in the overlap function over time.
    It is assumed that the overlap models should not vary significantly from month to month (relative difference should be less than 10%).
    
    Parameters:
    location (str): The site location name.
    inst_id (str): The instrument ID.
    path_temp_model1 (str): Path to the first overlap model folder (usually the previous month).
    path_temp_model2 (str): Path to the second overlap model folder (usually the current month).
    outfolder (str): Path to the output folder for saving comparison plots.
    
    Returns:
    int: Returns 1 if significant differences are found, otherwise 0.
    '''
    print(f"Comparing models for {location}:")

    filename_model1 = glob.glob(f"{path_temp_model1}/Overlap_correction_model_{location}_*_{inst_id}.nc")
    filename_model2 = glob.glob(f"{path_temp_model2}/Overlap_correction_model_{location}_*_{inst_id}.nc")
    
    # Reading the overlap model for the tub:
    model1 = xr.open_dataset(filename_model1[0])
    model2 = xr.open_dataset(filename_model2[0])

    # Better maybe, compare the overlap functions for a given T directly:
    ref_ov = model1.overlap_ref.data
    overlap_corr1 = ref_ov / (0.01*(model1.a * T + model1.b) + 1)
    overlap_corr2 = ref_ov / (0.01*(model2.a * T + model2.b) + 1)

    rel_diff_overlap = (overlap_corr1 - overlap_corr2) / overlap_corr1

    # restrict to the range of interest (where a significant overlap still exists)
    rel_diff_overlap = rel_diff_overlap.where(ref_ov > 0.005)

    if outfolder is not None:
        fig, axs = plt.subplots(1, 2, figsize=(12, 6))
        overlap_corr1.plot(ax=axs[0], y='range', label=f"Ov in {path_temp_model1}")
        overlap_corr2.plot(ax=axs[0], y='range', label=f"Ov in {path_temp_model2}")
        axs[0].legend()
        rel_diff_overlap.plot(ax=axs[1], y='range', label='Relative difference')
        axs[1].set_xlim(-0.1, 0.1)

        for ax in axs:
            ax.grid()
            ax.set_ylim(0, MAX_RANGE)
        axs[0].set_title('Overlap functions')
        axs[1].set_title('Relative difference of monthly overlap functions')
        axs[0].set_ylabel('Range (m)')
        axs[1].set_xlabel('Relative difference')
        fig.suptitle(f"Comparison of overlap functions for {location}, {model1.attrs['wigos_station_id']}_{inst_id}")
        plt.tight_layout(rect=[0, 0.01, 0.99, 1])
        fig.savefig(f"{outfolder}/{location}_{inst_id}_compare_overlap_functions.png", format='png')
        plt.close(fig)

    
    # Collect locations and inst_ids where the relative difference is above 0.1
    # Check if any difference is above 0.1, raise a warning and add the location and inst_id to the list
    if (np.abs(rel_diff_overlap) > 0.1).any():
        print(f"Warning: Significant differences found in overlap functions for {location} ({inst_id}). Check the plots for details.")
        above_threshold = 1
    else:
        above_threshold = 0
    return above_threshold
        
def apply_overlap_daily(date, wigos, inst_id, path_l1, resample_l1, path_temp_model, outfolder):
    '''
    Apply the temperature overlap model to the L1 data for a given date.
    This function reads the L1 data, applies the overlap correction based on the temperature model, and plots the results.
    '''

    year = date.strftime("%Y")
    month = date.strftime("%m")
    day = date.strftime("%d")

    filename_l1 = f"{path_l1}/{wigos}/{year}/{month}/L1_{wigos}_{inst_id}{year}{month}{day}.nc"
    print (filename_l1)

    ## extract data
    L1_ds = xr.open_dataset(filename_l1, engine='netcdf4')
    if resample_l1 is not None:
        print('resampling L1 data to ', resample_l1)
        L1_ds = L1_ds.resample(time=resample_l1).median()
    rcs_0 = L1_ds.rcs_0
    rcs_0_corr = rcs_0.copy(deep=True)
    print (L1_ds)
    
   # Reading optical module id to find the right model
    tub = L1_ds.attrs['optical_module_id']
    print (tub)

    # reading site location and instrument id from the attributes
    site_location = L1_ds.attrs['site_location'].split(',')[0]
    assert L1_ds.attrs['wigos_station_id'] == wigos, f"WIGOS ID mismatch: {L1_ds.attrs['wigos_station_id']} != {wigos}"
    assert str(L1_ds.attrs['instrument_id']) == str(inst_id), f"Instrument ID mismatch: {L1_ds.attrs['instrument_id']} != {inst_id}"

    # Reading the overlap model for the tub, stored in YYYYMM folder:
    #path_temp_model = path_temp_model + date.strftime("%Y%m") + '/'
    model_python = f"{path_temp_model}/Overlap_correction_model_{site_location}_{tub}_{inst_id}.nc"
    print (model_python)

    # print('Temperature (in °C ??)')
    L1_temp_int = np.array(L1_ds.temp_int.data - 273.15) #

    model_python_ds = xr.open_dataset(model_python)
    # print ('TEMP MODEL : ')
    # print (model_python_ds)

    ref_ov = model_python_ds.overlap_ref.data

    ## apply correction on raw data
    print ('apply correction on RCS data')

    diff_z = np.nan*rcs_0
    
    print(diff_z.shape)
    
    for i, t in enumerate(L1_temp_int):
        diff_z[i, :] = t*model_python_ds.a.data + model_python_ds.b.data
    print('Adding correction to RCS 0')

    overlap_corr = ref_ov / (0.01*diff_z + 1)
    rcs_0_corr = rcs_0 * (0.01*diff_z + 1)

    ## plot results
    print ('Plot results')

    fig, axs = plt.subplots(3, 2, figsize=(16,12))
    fig.suptitle(L1_ds.attrs['site_location'])

    rcs_0_plot = np.log10(np.abs(rcs_0.where(rcs_0.range<MAX_RANGE, drop=True)))
    rcs_corr_plot = np.log10(np.abs(rcs_0_corr.where(rcs_0_corr.range<MAX_RANGE, drop=True)))
    
    rcs_0_plot.plot(ax=axs[0,0], x='time',y='range', vmin=0, vmax=6, cmap='viridis', cbar_kwargs={'label': "log10(RCS)"})
    rcs_corr_plot.plot(ax=axs[1,0], x='time',y='range', vmin=0, vmax=6, cmap='viridis', cbar_kwargs={'label': "log10(RCScorr)"})

    #computed_diff = (rcs_0_corr - rcs_0)/rcs_0

    diff_z.where(diff_z.range<MAX_RANGE, drop=True).plot(ax=axs[2,0], x='time',y='range', vmin=-75, vmax=75, cmap='coolwarm', cbar_kwargs={'label': "(RCScorr - RCS)/RCS"})
    #computed_diff.where(diff_z.range<max_range, drop=True).plot(ax=axs[3], x='time',y='range')
    #axs[0].contourf(rcs_0.time, rcs_0_plot.range, rcs_0_plot.T, vmin=1, vmax=1e6, locator=ticker.LogLocator())
    #corr = axs[1].contourf(rcs_0.time, rcs_corr_plot.range, rcs_corr_plot.T, vmin=1, vmax=1e6, locator=ticker.LogLocator())
    axs[0,0].set_title('raw signal')
    axs[1,0].set_title('corrected signal')
    axs[0,0].set_ylabel('Range (m)')

    # Add the gradient of RCS to evaluate the model:
    rcs_0.differentiate('range').plot(ax=axs[0,1], x='time', vmin=-1000, vmax=1000)
    rcs_0_corr.differentiate('range').plot(ax=axs[1,1], x='time', vmin=-1000, vmax=1000)
    axs[0,1].set_ylim(0, MAX_RANGE)
    axs[1,1].set_ylim(0, MAX_RANGE)

    (L1_ds.temp_int - 273.15).plot(ax=axs[2,1], x='time')

    #plt.colorbar(corr, ax=axs[1])
    plt.tight_layout(rect=[0, 0.01, 0.99, 1])

    fig.savefig(f"{outfolder}{wigos}_{inst_id}{year}{month}{day}.png", format='png')
    plt.close(fig)

    # Now plot the averaged correction:
    fig, axs = plt.subplots(1, 3, sharey=True, figsize=(12,8))
    diff_z.mean(dim='time').plot(ax=axs[0], y='range')
    axs[0].set_xlabel('Mean rel diff [%]')
    overlap_corr.mean(dim='time').plot(ax=axs[1], y='range', label='corrected fc')
    axs[1].plot(ref_ov, diff_z.range, label='reference fc')
    axs[1].set_xlabel('Overlap function')
    axs[1].legend()
    axs[2].set_xlabel('Rel Diff vs T [%]')
    axs[2].set_ylabel('')

    # Add correction as function of T in 3rd plot:
    temperature = np.arange(10,40,2)
    color = mpl.cm.cividis(np.linspace(0, 1, len(temperature)))
    for temp, col in zip(temperature, color):
        diff_zt = temp*model_python_ds.a.data + model_python_ds.b.data
        axs[2].plot(diff_zt, diff_z.range, c=col)

    norm = mpl.colors.Normalize(vmin=temperature.min(), vmax=temperature.max())
    cmap = mpl.cm.ScalarMappable(norm=norm, cmap=mpl.cm.cividis)
    cmap.set_array([])

    for ax in axs:
        ax.grid()
        ax.set_ylim(0, MAX_RANGE)

    fig.colorbar(cmap, ticks=temperature, label='Temperature (°C)', ax=axs[2])
    fig.suptitle(f"Overlap correction for {L1_ds.attrs['site_location']}, {wigos}_{inst_id} on {year}-{month}-{day}")

    plt.tight_layout(rect=[0, 0.01, 0.99, 1])
    fig.savefig(f"{outfolder}{wigos}_{inst_id}{year}{month}{day}_corr.png", format='png')
    plt.close(fig)

def validate_overlap_model_monthly(path_temp_model_basepath, date, path_l1, outfolder):
    '''
    Validate the temperature overlap models on a given month.
    This function checks if the overlap models for the current month and the previous month exist.
    If the previous month's model does not exist, it plots the current month's model.
    If both models exist, it compares them and applies the overlap correction if significant differences are found.
    
    
    Parameters:
    path_temp_model_basepath (str): Base path to the temperature model folder.
    date (datetime.date): The date for which the models are validated.
    path_l1 (str): Path to the L1 data folder.
    outfolder (str): Path to the output folder for saving plots.
    
    
    '''
    print("Validating overlap model monthly...")
    current_month = datetime.today().strftime('%Y%m')

    path_temp_model = path_temp_model_basepath + current_month + '/'
    path_temp_model_previous_month = path_temp_model_basepath + (datetime.today() - timedelta(days=30)).strftime("%Y%m") + '/'

    # Loop through all models in the folder
    models = glob.glob(f"{path_temp_model}/Overlap_correction_model_*.nc")
    if not models:
        print(f"No models found in {path_temp_model}.")
        return
    
    print(f"Found {len(models)} models for {current_month}.")
    for model_file in models:
        try:
            print(f"Processing model: {model_file}")
            model_ds = xr.open_dataset(model_file)

            # Extract the site name and tub from the attrs:
            site_name_full = model_ds.attrs.get('site_location', 'Unknown')
            site_name = site_name_full.split(',')[0]  
            serlom = model_ds.attrs.get('serlom', 'Unknown')
            inst_id = model_ds.attrs.get('instrument_id', 'Unknown')
            print(f"Site: {site_name}, Optical Module ID: {serlom}")
            # Check if the model for the previous month exists
            model_file_previous_month = f"{path_temp_model_previous_month}/Overlap_correction_model_{site_name}_{serlom}_{inst_id}.nc"

            if not glob.glob(model_file_previous_month):
                print(f"No previous month model found for {site_name} with optical module {serlom}. Plotting this new model")
                above_threshold = 1
            else:
                print(f"Found previous month model: {model_file_previous_month}")
                above_threshold = compare_overlap_functions(site_name, inst_id, path_temp_model1=path_temp_model, path_temp_model2=path_temp_model_previous_month, outfolder=outfolder)
            
            if above_threshold:
                apply_overlap_daily(date, wigos=model_ds.attrs['wigos_station_id'], inst_id=inst_id, path_l1=path_l1, resample_l1=None, path_temp_model=path_temp_model, outfolder=outfolder)
        except Exception as e:
            print(f"Error processing model {model_file}: {e}")

def main():
    '''
    Main function to apply the temperature overlap model validation for monthly monitoring.
    It sets the paths for the temperature model, L1 data, and output folder.
    It uses the current date to determine the month for which the validation is performed.
    The default date for validation is set to the 15th of the previous month.
    '''
    print("Starting main function for overlap model validation...")
    today = datetime.today() 
    monthly_str = today.strftime('%Y%m')
    
    # Define paths
    path_temp_model_base = '/product_data/data/pay/REM/ACQ/E_PROFILE_ALC/Overlap/TEMP_MODELS/'
    path_l1 ='/product_data/data/zue/E_PROFILE/ALC/L1_FILES'
    outfolder = '/product_data/data/pay/REM/ACQ/E_PROFILE_ALC/Overlap/TEMP_MODELS/' + monthly_str + '/'

    # By default, use the 15th of the previous month
    time_to_apply = today.replace(day=15) - timedelta(days=30)

    validate_overlap_model_monthly(path_temp_model_basepath=path_temp_model_base, date=time_to_apply, path_l1=path_l1, outfolder=outfolder)
    
if __name__ == '__main__':
    main()
    print("Overlap model application completed.")

    
